### ISSUE TITLE
Correct prototype for _InitObject

### ISSUE THREAD

**Issue by futtersack** [mdave/nektar-driftwave#4]
Seems newest Nektar++ now need an argument to init the equation system.

Need to change to : void DriftWaveSystem::v_InitObject(bool DeclareField)

**Comment by matt-graham** [comment]
It looks like this might have been done in 08fbfc0dff38efed16772df4ea6decb76b8319b0 which is now in `master`?

**Comment by CFD-Xing** [comment]
@matt-graham Yes, this issue can be closed.

**Comment by mdave** [comment]
Thanks @CFD-Xing, will close this one now.
